apiVersion: v1
kind: Service
metadata:
  name: goapp-service
spec:
  # para acessar de forma externa, já criará um Ip externo
  type: LoadBalancer
  selector:
    app: goapp
  ports:
    - port: 8888
      targetPort: 8888
